version: '3.7'
services:
  postgres:
    image: postgres:15.2
    restart: always
    environment:
      - POSTGRES_DB=recipe_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5438:5432'
    volumes:
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./sql/fill_permissions.sql:/docker-entrypoint-initdb.d/fill_permissions.sql