package com.jackbracey.recipeapi.POJOs;

public enum Permissions {

    GET_MEASUREMENT,
    GET_RECIPE,
    CREATE_RECIPE,
    EDIT_RECIPE,
    DELETE_RECIPE,
    GET_PERMISSION,
    CREATE_PERMISSION,
    REMOVE_PERMISSION,
    ASSIGN_PERMISSION,
    GET_API_KEY,
    CREATE_API_KEY,
    REMOVE_API_KEY,
    GET_FEATURE_FLAG,
    CREATE_FEATURE_FLAG,
    DELETE_FEATURE_FLAG,
    DEV_TEST_ACCOUNT;

}
